name: CMake

on:
  push:
    branches: [ builds ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true

    - name: Set Up Dependencies
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install g++-12 libgtk-3-dev libsdl2-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=g++-12 -DCMAKE_C_COMPILER=gcc-12

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
    - name: Create Archive
      run: |
        mkdir upload
        ls build/CMakeFiles/Ortin.dir/
        find ./ -name "Ortin"
        mv build/Ortin upload/
        mv LICENSE upload/
        cd upload
        tar -cavf ../ortin_linux.zip *
        tar -cavf ../ortin_linux.tar.gz *
        cd ..

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "latest"
        prerelease: true
        name: "Development Build"
        files: |
          ortin_linux.zip
          ortin_linux.tar.gz

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true

    - name: Set Up Dependencies
      run: |
        vcpkg install sdl2:x64-windows

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake "-DCMAKE_C_COMPILER:FILEPATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm\x64\bin\clang.exe" "-DCMAKE_CXX_COMPILER:FILEPATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm\x64\bin\clang.exe" -G Ninja

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Create Archive
      run: |
        mkdir upload
        ls build/CMakeFiles/Ortin.dir/
        mv build/Ortin.exe upload/
        mv build/SDL2.dll upload/
        mv LICENSE upload/
        cd upload
        tar -cavf ../ortin_windows.zip *
        cd ..

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "latest"
        prerelease: true
        name: "Development Build"
        files: |
          ortin_windows.zip
